In [1]:
import numpy as np

In [2]:
print("a   b   a and b   a or b   not a\n"
      "--------------------------------")

for a in [False, True]:
    for b in [False, True]:
        print(f"{a:1} {b:3} {a and b:6} {a or b:8} {not a:7}")

a   b   a and b   a or b   not a
--------------------------------
0   0      0        0       1
0   1      0        1       1
1   0      0        1       0
1   1      1        1       0


In [3]:
name = "Elnur"
print(f'{name:10} + {name:1}')

Elnur      + Elnur


In [4]:
np.logspace(1, 2).reshape(25,2)

array([[ 10.        ,  10.48113134],
       [ 10.98541142,  11.51395399],
       [ 12.06792641,  12.64855217],
       [ 13.25711366,  13.89495494],
       [ 14.56348478,  15.26417967],
       [ 15.9985872 ,  16.76832937],
       [ 17.57510625,  18.42069969],
       [ 19.30697729,  20.23589648],
       [ 21.20950888,  22.22996483],
       [ 23.29951811,  24.42053095],
       [ 25.59547923,  26.82695795],
       [ 28.11768698,  29.47051703],
       [ 30.88843596,  32.37457543],
       [ 33.93221772,  35.56480306],
       [ 37.2759372 ,  39.06939937],
       [ 40.94915062,  42.9193426 ],
       [ 44.98432669,  47.14866363],
       [ 49.41713361,  51.79474679],
       [ 54.28675439,  56.89866029],
       [ 59.63623317,  62.50551925],
       [ 65.51285569,  68.6648845 ],
       [ 71.9685673 ,  75.43120063],
       [ 79.06043211,  82.86427729],
       [ 86.85113738,  91.0298178 ],
       [ 95.40954763, 100.        ]])

## Time comparison

In [5]:
import time
mat1 = np.random.rand(50, 50)
mat2 = np.array(mat1)
t = time.time()
mat3 = np.dot(mat2, mat2)
nptime = time.time() - t
mat3 = np.zeros([50, 50])
t = time.time()
for i in range(50):
    for k in range(50):
        for j in range(50):
            mat3[i][k] = mat3[i][k] + mat1[i][j] * mat1[j][k]
pytime = time.time() - t
times = str(pytime / nptime)
print("NumPy is " + times + " times faster!")

NumPy is 18.2049733161228 times faster!


In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [9]:
np.linspace(10,30,50,endpoint=False)

array([10. , 10.4, 10.8, 11.2, 11.6, 12. , 12.4, 12.8, 13.2, 13.6, 14. ,
       14.4, 14.8, 15.2, 15.6, 16. , 16.4, 16.8, 17.2, 17.6, 18. , 18.4,
       18.8, 19.2, 19.6, 20. , 20.4, 20.8, 21.2, 21.6, 22. , 22.4, 22.8,
       23.2, 23.6, 24. , 24.4, 24.8, 25.2, 25.6, 26. , 26.4, 26.8, 27.2,
       27.6, 28. , 28.4, 28.8, 29.2, 29.6])

In [10]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[:5:-1]

array([9, 8, 7, 6])

In [12]:
arr[5:2:-1]

array([5, 4, 3])

In [13]:
arr3 = np.array(
[[4, 8, 5],
[9, 3, 4],
[1, 0, 6]])

In [14]:
arr3

array([[4, 8, 5],
       [9, 3, 4],
       [1, 0, 6]])

In [15]:
column = arr3[:, 1]
column

array([8, 3, 0])

In [16]:
column.base

array([[4, 8, 5],
       [9, 3, 4],
       [1, 0, 6]])

In [17]:
elem = column[1:2]
elem

array([3])

In [18]:
elem[0] = 3

In [19]:
arr3

array([[4, 8, 5],
       [9, 3, 4],
       [1, 0, 6]])

In [20]:
arr3[:,[0,2]]

array([[4, 5],
       [9, 4],
       [1, 6]])

In [21]:
arr3[0:3:2,0:3:2]

array([[4, 5],
       [1, 6]])

In [22]:
a = np.array([3, 8, 4, 1, 9, 5, 2])
b = np.array([2, 3, 5, 6, 11, 15, 17])
c = (a % 2 == 0) | (b % 3 == 0) # or
c

array([False,  True,  True,  True, False,  True,  True])