In [7]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError:
        return False
        

In [9]:
isiterable("44")

True

In [18]:
s = r'this\has\no\special\characters'

In [19]:
s

'this\\has\\no\\special\\characters'

In [20]:
d = 'this\has\no\special\characters'

In [21]:
d

'this\\has\no\\special\\characters'

In [1]:
x = 5
'Non-negative' if x >= 0 else 'Negative'

'Non-negative'

In [2]:
pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'),('Schilling', 'Curt')]

In [8]:
f,l = zip(*pitchers)

In [9]:
f

('Nolan', 'Roger', 'Schilling')

In [10]:
l

('Ryan', 'Clemens', 'Curt')

In [11]:
d1 ={'a':1, 'b':2}

In [12]:
d1['c']=3

In [15]:
import numpy as np

In [19]:
print(np.__version__)

1.26.4


In [21]:
data = np.random.randn(2, 3)

In [22]:
data

array([[-0.86816548, -0.67258087,  0.34641342],
       [-1.35675878,  0.44637128, -0.78582273]])

In [24]:
z = np.zeros([5,4])

In [25]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
z.reshape(10,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])